version: "3"

services:
  web:
    container_name: api_app_nginx
    image: nginx
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - .:/usr/share/nginx/html
    ports:
      - 80:80
    environment:
      - NGINX_HOST=api.corp.loc
      - NGINX_PORT=80
      - FPM_PORT=9000
    depends_on:
      - db
      - redis
      - php-fpm
    links:
      - db
      - redis
      - php-fpm

  db:
    container_name: api_app_db
    image: mysql
    environment:
      - MYSQL_DATABASE=corp
      - MYSQL_USER=corp
      - MYSQL_PASSWORD=corp
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306

  redis:
    container_name: api_app_redis
    image: redis
    ports:
      - 6379:6379

  composer:
    container_name: api_app_composer
    image: composer
    volumes:
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    command: "composer i"



  php-fpm:
    container_name: api_app_phpfpm
    build: .
    volumes:
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    ports:
      - 9000:9000
    links:
      - db
      - redis
    depends_on:
      - composer